
version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate the storage code for sso"
    cmds:
      - mkdir -p ./storage
      - go run ./cmd/migrator -storage=./storage/sso.db -migrations=./migrations